### ISSUE TITLE
Non integer problem numbering

### ISSUE THREAD

**Issue by natestemen** [artemmavrin/latex-homework#6]
I'd like to be able to have exercises numbered as `2.1`, `2.2`, .... I've tried using `\problemnumber{2.1}`, but this doesn't seem to work because of the period. I even tried `\problemnumber{2\.1}`, but again same problem.

Perhaps this isn't possible, but would be good to verify.

**Comment by artemmavrin** [comment]
I don't know a nice way of doing this unfortunately, since the `problem` environment gets its numbering behavior from `amsthm`'s theorem-like environments. As a result, `\problemnumber` expects an integer. This is the line to blame:
https://github.com/artemmavrin/latex-homework/blob/1173aa780847175fcc0adde63cf06d6773469e50/homework.cls#L152

---

One hacky workaround would be to add the following to the preamble of your `.tex` file:

```latex
\makeatletter
\numberwithin{@problem}{section}
\makeatother
```

This makes the problem numbers depend on the current section number. Then you can set the section number to, e.g., 2 in the body of your `.tex` file:

```latex
\setcounter{section}{2}
```

The problems will be numbered 2.1, 2.2, etc, and you can still use `\problemnumber` to set the `n` in `2.n`. Also, you can switch to a different prefix by changing the `section` counter again.

---

Here's a minimal working example:

```latex
\documentclass{homework}

\name{Name}
\course{Course}
\term{Term}
\hwnum{\#}

\makeatletter
\numberwithin{@problem}{section}
\makeatother

\begin{document}

\setcounter{section}{2}

\begin{problem}
A problem.
\end{problem}

\begin{solution}
A solution.
\end{solution}

\begin{problem}
Another problem.
\end{problem}

\begin{solution}
Another solution.
\end{solution}

\end{document}
```

Hope this helps!

**Comment by natestemen** [comment]
This worked perfectly. Thanks for your detailed answer with an example. I'll leave this open, but feel free to close it.

**Comment by natestemen** [comment]
Hey another question related to this. I now have a homework starting with question 3.14. I've tried setting the subsection counter, but that's not working either. In short, I can't figure out a way to start the counter from 3.14.

This may be a larger question than just this package and if that's the case no worries, I'll keep looking elsewhere, but thought I'd ask if this is possible.

**Comment by artemmavrin** [comment]
You can use `\problemnumber{14}` before the first question to set the problem number.

**Comment by natestemen** [comment]
Great, thanks so much for your help again!
